[build]
builder = "nixpacks"
buildCommand = "playwright install chromium; playwright install-deps; echo built!"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
